export enum ItemType {
  ARMOR,
  CONTAINER,
  DRUG,
  WEAPON,
  AMMO,
  MISC,
  KEY,
  MATERIAL,
  COUNT
}

export enum ItemFlags {
  OBJECT_HIDDEN = 0x01,
  OBJECT_IN_LEFT_HAND = 0x1000000,
  OBJECT_IN_RIGHT_HAND = 0x2000000,
  OBJECT_WORN = 0x4000000,
  OBJECT_IN_ANY_HAND = OBJECT_IN_LEFT_HAND | OBJECT_IN_RIGHT_HAND,
  OBJECT_EQUIPPED = OBJECT_IN_ANY_HAND | OBJECT_WORN,
}

export enum CaliberType {
  CALIBER_TYPE_NONE,
  CALIBER_TYPE_ROCKET,
  CALIBER_TYPE_FLAMETHROWER_FUEL,
  CALIBER_TYPE_C_ENERGY_CELL,
  CALIBER_TYPE_D_ENERGY_CELL,
  CALIBER_TYPE_223,
  CALIBER_TYPE_5_MM,
  CALIBER_TYPE_40_CAL,
  CALIBER_TYPE_10_MM,
  CALIBER_TYPE_44_CAL,
  CALIBER_TYPE_14_MM,
  CALIBER_TYPE_12_GAUGE,
  CALIBER_TYPE_9_MM,
  CALIBER_TYPE_BB,
  CALIBER_TYPE_45_CAL,
  CALIBER_TYPE_2_MM,
  CALIBER_TYPE_4_7_MM_CASELESS,
  CALIBER_TYPE_NH_NEEDLER,
  CALIBER_TYPE_7_62,
  CALIBER_TYPE_COUNT
}

export enum MaterialType {
  MATERIAL_TYPE_GLASS,
  MATERIAL_TYPE_METAL,
  MATERIAL_TYPE_PLASTIC,
  MATERIAL_TYPE_WOOD,
  MATERIAL_TYPE_DIRT,
  MATERIAL_TYPE_STONE,
  MATERIAL_TYPE_CEMENT,
  MATERIAL_TYPE_LEATHER,
  MATERIAL_TYPE_COUNT,
}

export enum DamageType {
  DAMAGE_TYPE_NORMAL,
  DAMAGE_TYPE_LASER,
  DAMAGE_TYPE_FIRE,
  DAMAGE_TYPE_PLASMA,
  DAMAGE_TYPE_ELECTRICAL,
  DAMAGE_TYPE_EMP,
  DAMAGE_TYPE_EXPLOSION,
  DAMAGE_TYPE_COUNT,
}
